name: '✨ Issue'
description: '이슈를 등록해 주세요.'
title: '[Type] '

body:

  - type: textarea
    attributes:
      label: '📄 Description'
      description: 이슈 내용을 작성해 주세요.
      placeholder: 구체적으로 작성해 주세요.
    validations:
      required: true

  - type: textarea
    attributes:
      label: '✅ To-do'
      description: 해야 하는 일을 작성해 주세요.
      placeholder: |
        - [ ] 해야 할 일 1
        - [ ] 해야 할 일 2
    validations:
      required: true

  - type: textarea
    attributes:
      label: '📎 ETC'
      description: 추가로 공유할 사항이 있으면 작성해 주세요.
